FROM python:3.11
WORKDIR /code
COPY . /code
RUN apt update
RUN apt install -y libgl1-mesa-glx libglib2.0-0
RUN pip install -r requirements.txt
CMD uvicorn main:app --reload
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]